{
 "title": "Nmap Dashboard",
 "description": "View and analyze Nmap results with this Grafana Dashboard. ",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Hosts Up",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "nmap_results",
     "rawSql": "SELECT COUNT(id) FROM nmap_results.hosts LIMIT 50 "
    }
   ]
  },
  {
   "title": "Operating Systems",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "nmap_results",
     "rawSql": "SELECT h.os, COUNT(*) AS os_count\nFROM hosts h\nGROUP BY h.os\nORDER BY os_count DESC;\n"
    }
   ]
  },
  {
   "title": "Unidentified Services (open port)",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "nmap_results",
     "rawSql": "SELECT \n    p.port,\n    CASE \n        WHEN p.service_name IS NULL OR p.service_name = '' THEN 'Unidentified Service'\n        ELSE 'Identified Service'\n    END AS service_status, \n    COUNT(*) AS service_count\nFROM ports p\nWHERE p.state = 'open'\nGROUP BY p.port, service_status\nORDER BY p.port ASC;\n"
    }
   ]
  },
  {
   "title": "Identified Services",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dataset": "nmap_results",
     "rawSql": "SELECT p.service_info, COUNT(*) AS count\nFROM ports p\nJOIN hosts h ON p.host_id = h.id\nJOIN scans s ON h.scan_id = s.id\nWHERE s.start_time >= $__from / 1000 \nAND (s.start_time + s.elapsed_time) < $__to / 1000\nAND p.service_info IS NOT NULL \nAND p.service_info <> ''\nGROUP BY p.service_info\nORDER BY count DESC;\n"
    }
   ]
  },
  {
   "title": "Open Ports",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "nmap_results",
     "rawSql": "SELECT COUNT(*) AS total_open_ports\nFROM ports\nWHERE state = 'open';\n"
    }
   ]
  },
  {
   "title": "Unique Ports",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "nmap_results",
     "rawSql": "SELECT COUNT(DISTINCT port) FROM nmap_results.ports LIMIT 50 "
    }
   ]
  },
  {
   "title": "Open Ports Found",
   "type": "barchart",
   "gridPos": { "h": 5, "w": 10, "x": 2, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dataset": "nmap_results",
     "rawSql": "SELECT p.port, COUNT(p.port) AS open_port_count\nFROM ports p\nWHERE p.state = 'open'\nGROUP BY p.port\nORDER BY open_port_count DESC;\n"
    }
   ]
  },
  {
   "title": "Scans",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "nmap_results",
     "rawSql": "SELECT COUNT(DISTINCT id) FROM nmap_results.scans LIMIT 50 "
    }
   ]
  },
  {
   "title": "CHANGE UPDATE",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "dataset": "nmap_results",
     "rawSql": "SELECT description, change_type, FROM_UNIXTIME(detected_time) AS detected_time_readable\nFROM change_log\nORDER BY detected_time DESC;\n"
    }
   ]
  },
  {
   "title": "Live Hosts and Open Ports over Time",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "dataset": "nmap_results",
     "rawSql": "SELECT \n    DATE_SUB(FROM_UNIXTIME(cast(s.start_time as SIGNED)), INTERVAL 3 HOUR) AS scan_time,\n    COUNT(h.id) AS live_hosts_count,\n    SUM(h.ports_open) AS open_ports_count\nFROM scans s\nJOIN hosts h ON s.id = h.scan_id\nGROUP BY scan_time\nORDER BY scan_time ASC;\n"
    }
   ]
  },
  {
   "title": "Port Tested Per Second by Host",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "dataset": "nmap_results",
     "rawSql": "SELECT \n    ip,\n    (ports_tested / ((last_seen - first_seen) / 1000)) AS ports_tested_per_second\nFROM hosts\nWHERE first_seen IS NOT NULL AND last_seen IS NOT NULL;\n"
    }
   ]
  },
  {
   "title": "Service Detection Dashboard",
   "type": "table",
   "gridPos": { "h": 21, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "dataset": "nmap_results",
     "rawSql": "SELECT h.ip, p.port, p.service_name, p.service_info, p.http_title, p.ssl_common_name, p.ssl_issuer\nFROM ports p\nJOIN hosts h ON p.host_id = h.id\nWHERE p.service_name IS NOT NULL\nORDER BY h.ip, p.port;\n"
    }
   ]
  },
  {
   "title": "Open Ports Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "dataset": "nmap_results",
     "rawSql": "SELECT \n  DATE_SUB(FROM_UNIXTIME(CAST(open_date AS SIGNED) / 1000), INTERVAL 3 HOUR) AS time,\n  COUNT(id) AS open_ports\nFROM ports\nWHERE open_date IS NOT NULL\nGROUP BY time\nORDER BY time;\n"
    }
   ]
  },
  {
   "title": "Closed ports over time",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "dataset": "nmap_results",
     "rawSql": "SELECT \n  DATE_SUB(FROM_UNIXTIME(CAST(close_date AS SIGNED) / 1000), INTERVAL 3 HOUR) AS time,\n  COUNT(id) AS closed_ports\nFROM ports\nWHERE close_date IS NOT NULL\nGROUP BY time\nORDER BY time;\n"
    }
   ]
  },
  {
   "title": "Network Health and Security Dashboard",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {
     "dataset": "nmap_results",
     "rawSql": "SELECT h.ip, p.port, p.protocol, p.service_name, p.service_info, CASE \n    WHEN p.service_info LIKE '%old%' OR p.service_info LIKE '%vulnerable%' THEN 'High Risk'\n    WHEN p.state = 'open' THEN 'Moderate Risk'\n    ELSE 'Low Risk'\nEND AS risk_level\nFROM ports p\nJOIN hosts h ON p.host_id = h.id\nWHERE p.state = 'open'\nORDER BY risk_level DESC, h.ip;\n"
    }
   ]
  },
  {
   "title": "Scans Loaded",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {
     "dataset": "nmap_results",
     "rawSql": "SELECT  FROM_UNIXTIME(start_time) AS scan_start_time_utc, command_line, elapsed_time, total_hosts, total_open_ports FROM nmap_results.scans LIMIT 50 "
    }
   ]
  }
 ]
}